// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAIRDas0Bk6xbI83w_nvEIu0UW-mtb_jw',
    appId: '1:1088927904602:web:964837755cb7ccb1d37963',
    messagingSenderId: '1088927904602',
    projectId: 'travel-app-1430f',
    authDomain: 'travel-app-1430f.firebaseapp.com',
    storageBucket: 'travel-app-1430f.firebasestorage.app',
    measurementId: 'G-M1CH9DKEC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJHCxQqZSpW-fz_pQ6hsW6WYNKdEBz4IU',
    appId: '1:1088927904602:android:cc832a7db2a20ec3d37963',
    messagingSenderId: '1088927904602',
    projectId: 'travel-app-1430f',
    storageBucket: 'travel-app-1430f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgMaFwO6cypb9aIYzSPOIXzqPYdK6bFMY',
    appId: '1:1088927904602:ios:dfdb3c887702495ed37963',
    messagingSenderId: '1088927904602',
    projectId: 'travel-app-1430f',
    storageBucket: 'travel-app-1430f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgMaFwO6cypb9aIYzSPOIXzqPYdK6bFMY',
    appId: '1:1088927904602:ios:dfdb3c887702495ed37963',
    messagingSenderId: '1088927904602',
    projectId: 'travel-app-1430f',
    storageBucket: 'travel-app-1430f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAIRDas0Bk6xbI83w_nvEIu0UW-mtb_jw',
    appId: '1:1088927904602:web:f5c9f6241436ebfad37963',
    messagingSenderId: '1088927904602',
    projectId: 'travel-app-1430f',
    authDomain: 'travel-app-1430f.firebaseapp.com',
    storageBucket: 'travel-app-1430f.firebasestorage.app',
    measurementId: 'G-K0T3ZQH192',
  );
}
